"""Handing the answers back to the shell that called the wizard.

A FILE, never stdout. The wizard writes its menus to the terminal and its
answers to a path the caller passed, so there is no `$( )` boundary for a stray
line to corrupt -- which is the failure the bash version guarded against by
routing every prompt to /dev/tty and is now impossible by construction.

Under `set -euo pipefail` three things matter:

- Every variable is emitted UNCONDITIONALLY, empty where there is no value. The
  callers read some of them unguarded, and `set -u` would abort on a missing one.
- `export`, not assignment. `ts_agents_apply_wizard` reads these from the
  ENVIRONMENT of a child process; a bare assignment would silently turn the
  agent wiring off.
- The file is written whole and renamed into place, so a crashed wizard cannot
  leave a half-written one for the caller to source.
"""

from __future__ import annotations

import json
import shlex
from pathlib import Path

from .flow import Answers

# The shell names, in the order the callers read them. Kept explicit rather than
# derived from the dataclass: the shell contract is not the Python field list,
# and a rename on one side must not silently change the other.
SHELL_NAMES: tuple[tuple[str, str], ...] = (
    ("TS_WIZ_PROFILE", "profile"),
    ("TS_WIZ_DEV", "development"),
    ("TS_WIZ_APP_CLASS", "app_class"),
    ("TS_WIZ_STARSHIP", "starship"),
    ("TS_WIZ_LEADER", "leader"),
    ("TS_WIZ_THEME", "theme"),
    ("TS_WIZ_TMUX", "tmux"),
    ("TS_WIZ_TERMINALS", "terminals"),
    ("TS_WIZ_WEZ_MUX", "wez_mux"),
    ("TS_WIZ_WEZ_RESTORE", "wez_restore"),
    ("TS_WIZ_ATUIN", "atuin"),
    ("TS_WIZ_APPS", "apps"),
    ("TS_WIZ_CC_TTS", "cc_tts"),
    ("TS_WIZ_CC_TTS_MESSAGE", "cc_tts_message"),
    ("TS_WIZ_CC_TTS_DAEMON", "cc_tts_daemon"),
    ("TS_WIZ_MEMORY_BACKEND", "memory_backend"),
    ("TS_WIZ_HEADROOM", "headroom"),
    ("TS_WIZ_HEADROOM_CURSOR", "headroom_cursor"),
    ("TS_WIZ_CAVEMAN", "caveman"),
    ("TS_WIZ_AGENTMEMORY", "agentmemory"),
    ("TS_WIZ_ASKED", "asked"),
)

# The PascalCase keys the pwsh hashtable already used, so every `$w.X` call site
# in windows-bootstrap.ps1 is unchanged.
JSON_NAMES: tuple[tuple[str, str], ...] = (
    ("Profile", "profile"),
    ("Development", "development"),
    ("AppClass", "app_class"),
    ("StarshipPreset", "starship"),
    ("Leader", "leader"),
    ("Theme", "theme"),
    ("Tmux", "tmux"),
    ("Terminals", "terminals"),
    ("WezMux", "wez_mux"),
    ("WezRestore", "wez_restore"),
    ("Atuin", "atuin"),
    ("Apps", "apps"),
    ("CcTts", "cc_tts"),
    ("CcTtsMessage", "cc_tts_message"),
    ("CcTtsDaemon", "cc_tts_daemon"),
    ("MemoryBackend", "memory_backend"),
    ("Headroom", "headroom"),
    ("HeadroomCursor", "headroom_cursor"),
    ("Caveman", "caveman"),
    ("Agentmemory", "agentmemory"),
    ("Asked", "asked"),
)


def _shell_value(value: object) -> str:
    if isinstance(value, list):
        # Space separated: the callers word-split this into positional args, and
        # that splitting is load-bearing (`ts_data_set_apps $TS_WIZ_APPS`).
        return " ".join(str(v) for v in value)
    return str(value)


def to_sh(answers: Answers) -> str:
    lines = ["# generated by tstack wizard; source it once, then delete it"]
    for name, field_name in SHELL_NAMES:
        raw = _shell_value(getattr(answers, field_name))
        if not raw.isascii() or "\n" in raw:
            # A value that cannot be emitted safely is a bug in a question, not
            # something to quote around. Better to fail than to write a file the
            # caller will source.
            raise ValueError(f"{name}: refusing to emit a non-ASCII or multi-line value")
        lines.append(f"export {name}={shlex.quote(raw)}")
    return "\n".join(lines) + "\n"


def to_json(answers: Answers) -> str:
    payload = {name: getattr(answers, field_name) for name, field_name in JSON_NAMES}
    return json.dumps(payload, indent=2) + "\n"


def write(path: Path, body: str) -> None:
    """Whole file, then rename. A crash cannot leave a partial one to source."""
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(body, encoding="utf-8")
    temporary.replace(path)
