# install-tts-daemon.ps1 — set up / remove the terminal-stack TTS daemon (ttsd).
#
# Idempotent. Called by the install wizard (daemon choice), `ts-config tts
# daemon on|install`, or by hand:
#   pwsh -File bootstrap\install-tts-daemon.ps1              # install + start
#   pwsh -File bootstrap\install-tts-daemon.ps1 -Uninstall   # stop + deregister
#   pwsh -File bootstrap\install-tts-daemon.ps1 -Uninstall -Purge  # + remove venv
#
# Mirrors the Kokoro stance: nothing is silently installed — if Python is
# missing, we print the winget one-liner and stop.

[CmdletBinding()]
param(
    [switch]$Uninstall,
    [switch]$Purge,
    [switch]$NoStart
)

$ErrorActionPreference = 'Stop'

$daemonRoot = Join-Path $env:LOCALAPPDATA 'terminal-stack\tts-daemon'
$venvDir    = Join-Path $daemonRoot 'venv'
$launcher   = Join-Path $daemonRoot 'run-daemon.cmd'
$runKeyPath = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
$runKeyName = 'terminal-stack-tts-daemon'
$sourceDir  = Split-Path -Parent $PSScriptRoot   # the clone this script runs from

function Get-TtsdPort {
    $cfg = Join-Path $env:USERPROFILE '.claude\tts\config.json'
    if (Test-Path -LiteralPath $cfg) {
        try {
            $port = (Get-Content $cfg -Raw | ConvertFrom-Json).daemon.port
            if ($port) { return [int]$port }
        } catch {}
    }
    return 8890
}

function Test-TtsdHealthy {
    param([int]$Port)
    try {
        $r = Invoke-WebRequest -Uri "http://127.0.0.1:$Port/healthz" -TimeoutSec 2 -UseBasicParsing
        return ($r.StatusCode -eq 200)
    } catch { return $false }
}

function Stop-Ttsd {
    param([int]$Port)
    if (-not (Test-TtsdHealthy -Port $Port)) { return }
    try {
        Invoke-WebRequest -Uri "http://127.0.0.1:$Port/v1/duck/release" -Method Post -TimeoutSec 3 -UseBasicParsing | Out-Null
    } catch {}
    try {
        Invoke-WebRequest -Uri "http://127.0.0.1:$Port/v1/shutdown" -Method Post -TimeoutSec 3 -UseBasicParsing | Out-Null
        Start-Sleep -Seconds 1
    } catch {}
}

$port = Get-TtsdPort

if ($Uninstall) {
    Stop-Ttsd -Port $port
    try { Remove-ItemProperty -Path $runKeyPath -Name $runKeyName -ErrorAction Stop } catch {}
    if ($Purge -and (Test-Path -LiteralPath $venvDir)) {
        Remove-Item -Recurse -Force -Confirm:$false -LiteralPath $venvDir
    }
    Write-Host 'tts daemon: stopped and removed from autostart' -ForegroundColor Green
    if (-not $Purge) { Write-Host "  (venv kept at $venvDir; -Purge removes it)" }
    exit 0
}

# ── 1. Python 3.10+ ────────────────────────────────────────────────────────────
$pyExe = $null; $pyArgs = @()
foreach ($candidate in @(
        @{ Exe = 'py'; Args = @('-3') },
        @{ Exe = 'python'; Args = @() })) {
    $cmd = Get-Command $candidate.Exe -ErrorAction SilentlyContinue
    if (-not $cmd) { continue }
    try {
        $ver = (& $cmd.Source @($candidate.Args + @('-c', 'import sys; print("%d.%d" % sys.version_info[:2])')) 2>$null | Select-Object -First 1)
        if ($ver -and ([version]$ver.Trim() -ge [version]'3.10')) {
            $pyExe = $cmd.Source; $pyArgs = $candidate.Args; break
        }
    } catch {}
}
if (-not $pyExe) {
    Write-Warning 'Python 3.10+ not found. Install it, then re-run:'
    Write-Host '  winget install Python.Python.3.12' -ForegroundColor Yellow
    Write-Host '  ts-config tts daemon install'
    exit 1
}

# ── 2. venv + deps (venv lives OUTSIDE the clone — ts-update never touches it) ─
if (-not (Test-Path -LiteralPath (Join-Path $venvDir 'Scripts\python.exe'))) {
    Write-Host "Creating venv at $venvDir ..."
    New-Item -ItemType Directory -Force -Path $daemonRoot | Out-Null
    & $pyExe @($pyArgs + @('-m', 'venv', $venvDir))
}
$venvPy = Join-Path $venvDir 'Scripts\python.exe'
Write-Host 'Installing/refreshing daemon dependencies ...'
& $venvPy -m pip install --quiet --disable-pip-version-check -r (Join-Path $sourceDir 'bootstrap\tts-daemon\requirements.txt')
if ($LASTEXITCODE -ne 0) { Write-Warning 'pip install failed'; exit 1 }

# ── 3. launcher (resolves the clone at LAUNCH time, so relocations survive) ────
$cmdLines = @(
    '@echo off'
    'rem terminal-stack ttsd launcher - generated by install-tts-daemon.ps1'
    'set "STACK=%LOCALAPPDATA%\terminal-stack\stack"'
    'if defined TERMINAL_STACK_DIR set "STACK=%TERMINAL_STACK_DIR%"'
    ('if not exist "%STACK%\bootstrap\tts-daemon\ttsd\__main__.py" set "STACK=' + $sourceDir + '"')
    ('start "" "' + (Join-Path $venvDir 'Scripts\pythonw.exe') + '" -m ttsd')
)
# pythonw needs the package on sys.path — run from the tts-daemon directory.
$cmdLines[-1] = 'cd /d "%STACK%\bootstrap\tts-daemon" && ' + $cmdLines[-1]
Set-Content -LiteralPath $launcher -Value $cmdLines -Encoding ASCII

# ── 4. autostart (HKCU Run — no admin, idempotent) ─────────────────────────────
New-ItemProperty -Path $runKeyPath -Name $runKeyName -Value "`"$launcher`"" -PropertyType String -Force | Out-Null

# ── 5. firewall rule for the WSL-facing listener (best effort; needs admin) ────
$ruleName = 'terminal-stack ttsd (WSL)'
if (-not (Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue)) {
    try {
        New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -Action Allow `
            -Protocol TCP -LocalPort $port -RemoteAddress 172.16.0.0/12 -Profile Any | Out-Null
        Write-Host "Firewall rule added for WSL → daemon (port $port)."
    } catch {
        Write-Host 'Note: could not add the WSL firewall rule (needs an elevated shell).' -ForegroundColor Yellow
        Write-Host "  Without it, WSL hooks fall back to direct playback (mirrored-networking WSL is unaffected)."
        Write-Host "  Elevated one-liner: New-NetFirewallRule -DisplayName '$ruleName' -Direction Inbound -Action Allow -Protocol TCP -LocalPort $port -RemoteAddress 172.16.0.0/12"
    }
}

# ── 6. start + probe ────────────────────────────────────────────────────────────
if (-not $NoStart) {
    if (Test-TtsdHealthy -Port $port) {
        Write-Host 'tts daemon: already running' -ForegroundColor Green
    } else {
        # Explicit cmd.exe host: Start-Process on a bare .cmd goes through
        # ShellExecute, which is flaky from non-interactive/interop contexts.
        Start-Process -FilePath "$env:ComSpec" -ArgumentList '/c', "`"$launcher`"" -WindowStyle Hidden
        $healthy = $false
        foreach ($i in 1..20) {
            Start-Sleep -Milliseconds 500
            if (Test-TtsdHealthy -Port $port) { $healthy = $true; break }
        }
        if ($healthy) {
            Write-Host "tts daemon: running on http://127.0.0.1:$port" -ForegroundColor Green
        } else {
            Write-Warning "daemon did not answer /healthz within 10s — check $daemonRoot\logs\ttsd.log"
            exit 1
        }
    }
}
exit 0
