"""`tstack ui` - the settings dashboard's read model and save path.

Textual is optional and probably not installed, so nothing here imports it. That
is not a gap: `tstack/ui/app.py` deliberately holds no rules, and every decision
the dashboard makes -- what a row says, what matches a filter, what a keypress
would write, and what gets refused -- lives in `model.py`, which is stdlib-only.

Every test uses a throwaway HOME. `docs/verifying-changes.md` section 4 is
explicit about it and the reason is not hypothetical: a dashboard test that
writes the developer's real chezmoi.toml corrupts the machine it protects.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tstack import platform as plat  # noqa: E402
from tstack import schema, store  # noqa: E402
from tstack.commands import ui as ui_cmd  # noqa: E402
from tstack.ui import model  # noqa: E402


@pytest.fixture(autouse=True)
def _throwaway_home(monkeypatch, tmp_path):
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setattr(Path, "home", staticmethod(lambda: home))
    monkeypatch.setattr(plat, "kind", lambda: plat.LINUX)
    monkeypatch.setattr(plat, "find_chezmoi", lambda: None)
    monkeypatch.setattr(store, "mirror", lambda: {})
    monkeypatch.setattr(store, "mirror_path", lambda: None)
    store.clear_cache()
    yield home
    store.clear_cache()


def test_every_setting_reaches_the_dashboard():
    """The whole point of the request this answers: the TUI configures all of it.

    Derived from the schema rather than from a list here, so a setting added
    tomorrow appears without anyone remembering to register it -- which is the
    failure this repo has had four times over, in four hand-maintained key lists.
    """
    rows = model.rows()
    assert {r.key for r in rows} == set(schema.BY_KEY)
    assert [r.key for r in rows] == [s.key for s in schema.SETTINGS], "declaration order"


def test_derived_settings_are_shown_and_refused_rather_than_hidden():
    """Knowing a value exists and is not yours to set is the point of listing it.

    `resolvedTheme` is regenerated by `chezmoi init` from `themeMode`, so writing
    it produces a value that survives exactly until the next save. Hiding it
    would leave someone hunting for where the palette comes from.
    """
    rows = {r.key: r for r in model.rows()}
    assert not rows["resolvedTheme"].editable
    assert rows["themeMode"].editable

    ok, message = model.save("resolvedTheme", "light")
    assert not ok
    assert "derived" in message.lower()
    assert not store.toml_path().exists(), "a refusal must not write anything at all"


def test_the_filter_searches_the_note_because_nobody_remembers_the_key():
    """The keys are camelCase internals. Someone looking for the Ollama endpoint
    types "ollama", and the note is where that word lives for several of them.
    """
    rows = model.rows()
    assert model.filter_rows(rows, "") == rows, "an empty filter hides nothing"

    by_note = {r.key for r in model.filter_rows(rows, "ollama")}
    assert "ccTtsOllamaUrl" in by_note
    assert "ccTtsSummarizer" in by_note, "found by its note, not by its key"

    assert {r.key for r in model.filter_rows(rows, "LEADERCHORD")} >= {"leaderChord"}
    assert model.filter_rows(rows, "no-such-setting-anywhere") == []


def test_an_empty_value_is_a_state_with_a_name():
    """`ccTtsSayVoice` unset means "the system voice" -- a real, chosen
    configuration. Rendered as a blank cell it reads as a bug in the dashboard.
    """
    rows = {r.key: r for r in model.rows()}
    assert rows["ccTtsSayVoice"].value == ""
    assert rows["ccTtsSayVoice"].display == "(unset)"
    assert rows["themeMode"].display == "dark"


def test_space_cycles_a_choice_and_wraps():
    """Two- and three-value settings do not need a dialog; one keystroke is the
    whole interaction, which is only true if it wraps."""
    rows = {r.key: r for r in model.rows()}
    theme = rows["themeMode"]
    assert theme.options == ("dark", "light", "follow")
    assert model.next_choice(theme) == "light"
    assert model.next_choice(theme, backwards=True) == "follow", "wraps the other way too"
    assert model.next_choice(rows["leaderChord"]) is None, "not a choice setting"


def test_cycling_from_an_unrecognised_value_lands_on_a_valid_one():
    """A value hand-edited into chezmoi.toml is not in `options`, so `.index()`
    raises. Falling back to the first option makes the keypress a repair rather
    than a crash."""
    rows = {r.key: r for r in model.rows()}
    stray = model.Row(**{**rows["themeMode"].__dict__, "value": "solarized"})
    assert model.next_choice(stray) == "dark"


def test_a_save_goes_through_the_command_line_setter_and_nothing_else():
    """store.py is the one writer, and a dashboard is exactly the kind of thing
    that grows a second one -- it already has the key, the value and the path.
    Routing through config.set_value is what keeps the schema's validation, the
    chezmoi re-init and the DERIVED refusal identical in both front ends.

    Asserted against the written chezmoi.toml rather than against `store.get`:
    the fixture pins a machine with no chezmoi binary, where reads correctly
    return defaults because there is nothing to run the template with. The file
    is the evidence that a write happened.
    """
    ok, message = model.save("themeMode", "light")
    assert ok, message
    assert 'themeMode = "light"' in store.toml_path().read_text(encoding="utf-8")
    assert "themeMode" in message

    ok, message = model.save("themeMode", "solarized")
    assert not ok
    assert "must be one of" in message
    body = store.toml_path().read_text(encoding="utf-8")
    assert 'themeMode = "light"' in body, "a rejected value must not overwrite a good one"
    assert "solarized" not in body

    ok, message = model.save("noSuchSetting", "x")
    assert not ok and "unknown setting" in message


def test_a_save_never_prints_into_the_rendered_screen(capsys):
    """`config.set_value` talks to a terminal this process has handed to Textual.
    An un-captured "saved: ..." line lands in the middle of the table."""
    model.save("themeMode", "light")
    captured = capsys.readouterr()
    assert captured.out == "", f"leaked to stdout: {captured.out!r}"


def test_a_failing_save_reports_rather_than_taking_the_dashboard_down(monkeypatch):
    """Whatever goes wrong underneath -- an unwritable config, a chezmoi that
    dies -- the dashboard must stay up and say so. A traceback out of a TUI event
    handler leaves a corrupted terminal."""
    from tstack.commands import config as config_cmd

    def explode(*a, **k):
        raise OSError("read-only file system")

    monkeypatch.setattr(config_cmd, "set_value", explode)
    ok, message = model.save("themeMode", "light")
    assert not ok
    assert "read-only file system" in message


def test_changed_compares_against_the_default_not_the_source(monkeypatch):
    """`source` answers a different question -- where the value was READ from --
    and a saved value identical to the default is not a change worth marking."""
    rows = {r.key: r for r in model.rows()}
    assert not model.changed(rows["themeMode"]), "dark is the default"

    monkeypatch.setattr(store, "chezmoi_data", lambda: {"themeMode": "light"})
    saved = {r.key: r for r in model.rows()}["themeMode"]
    assert saved.value == "light"
    assert model.changed(saved)

    monkeypatch.setattr(store, "chezmoi_data", lambda: {"themeMode": "dark"})
    same = {r.key: r for r in model.rows()}["themeMode"]
    assert same.source == schema.FROM_CHEZMOI, "it WAS read from the store"
    assert not model.changed(same), "...and it still is not a change"


def test_a_setting_that_needs_a_new_shell_says_so_before_the_edit():
    """Not after wondering why nothing happened. The flag is already in the
    schema; the dashboard's job is to put it where the cursor is."""
    rows = {r.key: r for r in model.rows()}
    assert rows["leaderChord"].after == "new shell"
    assert rows["themeMode"].after == ""


def test_missing_textual_is_an_instruction_not_a_traceback(monkeypatch, capsys):
    """Textual is the only third-party import in this program, and the reason
    everything else is stdlib-only is that a fresh machine must be able to run
    `tstack doctor` before anything is installed. So this command has to fail
    like a helpful message.
    """
    real_import = __import__

    def no_textual(name, *args, **kwargs):
        if name.startswith("textual") or name.endswith("ui.app"):
            raise ImportError("No module named 'textual'")
        return real_import(name, *args, **kwargs)

    monkeypatch.setattr("builtins.__import__", no_textual)
    code = ui_cmd.main([])
    monkeypatch.undo()
    assert code == 1
    err = capsys.readouterr().err
    assert "pip install" in err or "uv tool install" in err
    assert "Traceback" not in err
    assert "tstack config show" in err, "and it must name the way to do it meanwhile"


def test_ui_help_and_argument_handling():
    assert ui_cmd.main(["-h"]) == 0
    assert ui_cmd.main(["--help"]) == 0
    assert ui_cmd.main(["nonsense"]) == 2, "usage errors are 2, like every other verb"


def test_ui_is_in_the_registry_on_both_platforms():
    """A command not in commands.conf exists for `python -m tstack.main` and for
    nobody else: the shell shims, the completions and `tstack --help` all read
    that file and nothing else."""
    from tstack import registry

    row = registry.get("ui")
    assert row is not None, "tstack ui is missing from commands.conf"
    assert row.posix == "python" and row.windows == "python"
    assert row.summary
