"""`tstack ui` - the settings dashboard's read model and save path.

Textual is optional and probably not installed, so nothing here imports it. That
is not a gap: `tstack/ui/app.py` deliberately holds no rules, and every decision
the dashboard makes -- what a row says, what matches a filter, what a keypress
would write, and what gets refused -- lives in `model.py`, which is stdlib-only.

Every test uses a throwaway HOME. `docs/verifying-changes.md` section 4 is
explicit about it and the reason is not hypothetical: a dashboard test that
writes the developer's real chezmoi.toml corrupts the machine it protects.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tstack import platform as plat  # noqa: E402
from tstack import schema, store  # noqa: E402
from tstack.commands import ui as ui_cmd  # noqa: E402
from tstack.ui import model  # noqa: E402


def model_paths():
    """The `paths` module as `ui/model.py` imported it, for monkeypatching."""
    from tstack import paths

    return paths


@pytest.fixture(autouse=True)
def _throwaway_home(monkeypatch, tmp_path):
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setattr(Path, "home", staticmethod(lambda: home))
    monkeypatch.setattr(plat, "kind", lambda: plat.LINUX)
    monkeypatch.setattr(plat, "find_chezmoi", lambda: None)
    monkeypatch.setattr(store, "mirror", lambda: {})
    monkeypatch.setattr(store, "mirror_path", lambda: None)
    store.clear_cache()
    yield home
    store.clear_cache()


def test_every_setting_reaches_the_dashboard():
    """The whole point of the request this answers: the TUI configures all of it.

    Derived from the schema rather than from a list here, so a setting added
    tomorrow appears without anyone remembering to register it -- which is the
    failure this repo has had four times over, in four hand-maintained key lists.

    Scoped to the SETTINGS store, because the dashboard also carries rows that
    are deliberately not chezmoi keys: agentmemory's chat provider (the stack
    .env) and the workspace root (~/.zshrc.local). Unscoped, this passed only
    while `llm_rows()` happened to return nothing on the machine running it --
    a green assertion that was not testing what it said.
    """
    rows = [r for r in model.rows() if r.store == model.SETTINGS]
    assert {r.key for r in rows} == set(schema.BY_KEY)
    assert [r.key for r in rows] == [s.key for s in schema.SETTINGS], "declaration order"


def test_derived_settings_are_shown_and_refused_rather_than_hidden():
    """Knowing a value exists and is not yours to set is the point of listing it.

    `resolvedTheme` is regenerated by `chezmoi init` from `themeMode`, so writing
    it produces a value that survives exactly until the next save. Hiding it
    would leave someone hunting for where the palette comes from.
    """
    rows = {r.key: r for r in model.rows()}
    assert not rows["resolvedTheme"].editable
    assert rows["themeMode"].editable

    ok, message = model.save("resolvedTheme", "light")
    assert not ok
    assert "derived" in message.lower()
    assert not store.toml_path().exists(), "a refusal must not write anything at all"


def test_the_filter_searches_the_note_because_nobody_remembers_the_key():
    """The keys are camelCase internals. Someone looking for the Ollama endpoint
    types "ollama", and the note is where that word lives for several of them.
    """
    rows = model.rows()
    assert model.filter_rows(rows, "") == rows, "an empty filter hides nothing"

    by_note = {r.key for r in model.filter_rows(rows, "ollama")}
    assert "ccTtsOllamaUrl" in by_note
    assert "ccTtsSummarizer" in by_note, "found by its note, not by its key"

    assert {r.key for r in model.filter_rows(rows, "LEADERCHORD")} >= {"leaderChord"}
    assert model.filter_rows(rows, "no-such-setting-anywhere") == []


def test_an_empty_value_is_a_state_with_a_name():
    """`ccTtsSayVoice` unset means "the system voice" -- a real, chosen
    configuration. Rendered as a blank cell it reads as a bug in the dashboard.
    """
    rows = {r.key: r for r in model.rows()}
    assert rows["ccTtsSayVoice"].value == ""
    assert rows["ccTtsSayVoice"].display == "(unset)"
    assert rows["themeMode"].display == "dark"


def test_space_cycles_a_choice_and_wraps():
    """Two- and three-value settings do not need a dialog; one keystroke is the
    whole interaction, which is only true if it wraps."""
    rows = {r.key: r for r in model.rows()}
    theme = rows["themeMode"]
    assert theme.options == ("dark", "light", "follow")
    assert model.next_choice(theme) == "light"
    assert model.next_choice(theme, backwards=True) == "follow", "wraps the other way too"
    assert model.next_choice(rows["leaderChord"]) is None, "not a choice setting"


def test_cycling_from_an_unrecognised_value_lands_on_a_valid_one():
    """A value hand-edited into chezmoi.toml is not in `options`, so `.index()`
    raises. Falling back to the first option makes the keypress a repair rather
    than a crash."""
    rows = {r.key: r for r in model.rows()}
    stray = model.Row(**{**rows["themeMode"].__dict__, "value": "solarized"})
    assert model.next_choice(stray) == "dark"


def test_a_save_goes_through_the_command_line_setter_and_nothing_else():
    """store.py is the one writer, and a dashboard is exactly the kind of thing
    that grows a second one -- it already has the key, the value and the path.
    Routing through config.set_value is what keeps the schema's validation, the
    chezmoi re-init and the DERIVED refusal identical in both front ends.

    Asserted against the written chezmoi.toml rather than against `store.get`:
    the fixture pins a machine with no chezmoi binary, where reads correctly
    return defaults because there is nothing to run the template with. The file
    is the evidence that a write happened.
    """
    ok, message = model.save("themeMode", "light")
    assert ok, message
    assert 'themeMode = "light"' in store.toml_path().read_text(encoding="utf-8")
    assert "themeMode" in message

    ok, message = model.save("themeMode", "solarized")
    assert not ok
    assert "must be one of" in message
    body = store.toml_path().read_text(encoding="utf-8")
    assert 'themeMode = "light"' in body, "a rejected value must not overwrite a good one"
    assert "solarized" not in body

    ok, message = model.save("noSuchSetting", "x")
    assert not ok and "unknown setting" in message


def test_a_save_never_prints_into_the_rendered_screen(capsys):
    """`config.set_value` talks to a terminal this process has handed to Textual.
    An un-captured "saved: ..." line lands in the middle of the table."""
    model.save("themeMode", "light")
    captured = capsys.readouterr()
    assert captured.out == "", f"leaked to stdout: {captured.out!r}"


def test_a_failing_save_reports_rather_than_taking_the_dashboard_down(monkeypatch):
    """Whatever goes wrong underneath -- an unwritable config, a chezmoi that
    dies -- the dashboard must stay up and say so. A traceback out of a TUI event
    handler leaves a corrupted terminal."""
    from tstack.commands import config as config_cmd

    def explode(*a, **k):
        raise OSError("read-only file system")

    monkeypatch.setattr(config_cmd, "set_value", explode)
    ok, message = model.save("themeMode", "light")
    assert not ok
    assert "read-only file system" in message


def test_changed_compares_against_the_default_not_the_source(monkeypatch):
    """`source` answers a different question -- where the value was READ from --
    and a saved value identical to the default is not a change worth marking."""
    rows = {r.key: r for r in model.rows()}
    assert not model.changed(rows["themeMode"]), "dark is the default"

    monkeypatch.setattr(store, "chezmoi_data", lambda: {"themeMode": "light"})
    saved = {r.key: r for r in model.rows()}["themeMode"]
    assert saved.value == "light"
    assert model.changed(saved)

    monkeypatch.setattr(store, "chezmoi_data", lambda: {"themeMode": "dark"})
    same = {r.key: r for r in model.rows()}["themeMode"]
    assert same.source == schema.FROM_CHEZMOI, "it WAS read from the store"
    assert not model.changed(same), "...and it still is not a change"


def test_a_setting_that_needs_a_new_shell_says_so_before_the_edit():
    """Not after wondering why nothing happened. The flag is already in the
    schema; the dashboard's job is to put it where the cursor is."""
    rows = {r.key: r for r in model.rows()}
    assert rows["leaderChord"].after == "new shell"
    assert rows["themeMode"].after == ""


def test_missing_textual_is_an_instruction_not_a_traceback(monkeypatch, capsys):
    """Textual is the only third-party import in this program, and the reason
    everything else is stdlib-only is that a fresh machine must be able to run
    `tstack doctor` before anything is installed. So this command has to fail
    like a helpful message.
    """
    real_import = __import__

    def no_textual(name, *args, **kwargs):
        if name.startswith("textual") or name.endswith("ui.app"):
            raise ImportError("No module named 'textual'")
        return real_import(name, *args, **kwargs)

    monkeypatch.setattr("builtins.__import__", no_textual)
    code = ui_cmd.main([])
    monkeypatch.undo()
    assert code == 1
    err = capsys.readouterr().err
    assert "pip install" in err or "uv tool install" in err
    assert "Traceback" not in err
    assert "tstack config show" in err, "and it must name the way to do it meanwhile"


def test_ui_help_and_argument_handling():
    assert ui_cmd.main(["-h"]) == 0
    assert ui_cmd.main(["--help"]) == 0
    assert ui_cmd.main(["nonsense"]) == 2, "usage errors are 2, like every other verb"


def test_ui_is_in_the_registry_on_both_platforms():
    """A command not in commands.conf exists for `python -m tstack.main` and for
    nobody else: the shell shims, the completions and `tstack --help` all read
    that file and nothing else."""
    from tstack import registry

    row = registry.get("ui")
    assert row is not None, "tstack ui is missing from commands.conf"
    assert row.posix == "python" and row.windows == "python"
    assert row.summary


# ------------------------------------------- the chat provider, which is not a setting


def test_the_llm_rows_appear_only_when_there_is_a_stack_env(monkeypatch, tmp_path):
    """AgentMemory's chat provider is not a saved setting -- it lives in the
    stack's .env, compose's own interpolation source. The dashboard shows it
    because "configure all this" means all of it, and a machine that has never
    run `tstack services bootstrap` has no such file to show.
    """
    from tstack.ui import model

    monkeypatch.setattr(model_paths(), "resolve_source_dir", lambda: tmp_path)
    assert model.llm_rows() == [], "no clone contents, nothing to offer"

    stack = tmp_path / "services" / "stacks" / "agentmemory"
    stack.mkdir(parents=True)
    (stack / ".env").write_text("OPENAI_BASE_URL=http://h:1/v1\n", encoding="utf-8")
    monkeypatch.setenv("TS_STACK_ROOT", str(tmp_path / "services" / "stacks"))
    rows = model.llm_rows()
    assert [r.key for r in rows] == ["OPENAI_BASE_URL", "OPENAI_MODEL"]
    assert all(r.store == model.LLM for r in rows), "they carry their own store tag"
    assert rows[0].value == "http://h:1/v1"
    assert rows[0].source == "stack .env"
    assert rows[1].source == "unset", "an unset model is a state worth naming"


def test_a_dashboard_save_of_the_endpoint_routes_to_the_env_not_the_store(monkeypatch, tmp_path):
    """Two stores, one screen. Routing on the row's tag is what keeps the
    settings writer the single writer for settings."""
    from tstack import llmconfig
    from tstack.ui import model

    stack = tmp_path / "services" / "stacks" / "agentmemory"
    stack.mkdir(parents=True)
    (stack / ".env").write_text("# empty\n", encoding="utf-8")
    monkeypatch.setattr(model_paths(), "resolve_source_dir", lambda: tmp_path)
    monkeypatch.setenv("TS_STACK_ROOT", str(tmp_path / "services" / "stacks"))

    ok, message = model.save_llm("OPENAI_BASE_URL", "http://host.docker.internal:11434/v1")
    assert ok, message
    assert "restart agentmemory" in message, "the setting is inert until it does"
    provider = llmconfig.read(tmp_path)
    assert provider.base_url == "http://host.docker.internal:11434/v1"
    assert provider.provider_label == "Ollama", "labelled from the endpoint, not left blank"
    assert not store.toml_path().exists(), "and nothing reached the settings store"


def test_clearing_the_endpoint_clears_the_model_and_the_labels(monkeypatch, tmp_path):
    """A half-cleared provider names one this machine no longer has: the compose
    file defaults the labels to OpenAI, so leaving them is worse than wrong."""
    from tstack import llmconfig
    from tstack.ui import model

    stack = tmp_path / "services" / "stacks" / "agentmemory"
    stack.mkdir(parents=True)
    (stack / ".env").write_text("# empty\n", encoding="utf-8")
    monkeypatch.setattr(model_paths(), "resolve_source_dir", lambda: tmp_path)
    monkeypatch.setenv("TS_STACK_ROOT", str(tmp_path / "services" / "stacks"))

    model.save_llm("OPENAI_BASE_URL", "https://api.openai.com/v1")
    model.save_llm("OPENAI_MODEL", "gpt-4o-mini")
    assert llmconfig.read(tmp_path).complete

    ok, message = model.save_llm("OPENAI_BASE_URL", "")
    assert ok and "cleared" in message
    provider = llmconfig.read(tmp_path)
    assert provider.base_url == "" and provider.model == ""
    assert provider.provider_label == llmconfig.UNCONFIGURED_PROVIDER


# ------------------------------------------- the missing-dependency message ----


def test_the_missing_textual_message_never_suggests_a_tool_installer():
    """`uv tool install textual` and `pipx install textual` both FAIL, everywhere.

    Both install APPLICATIONS into isolated venvs and refuse a package with no
    entry points; textual is a library, its CLI being the separate `textual-dev`
    package. This module shipped all three of

        uv tool install textual
        pipx install textual
        pip install --user textual

    and on an Omarchy box every one failed -- the first two for that reason, the
    third because Arch ships no bare `pip` and PEP 668 would refuse the write
    anyway. Advice that cannot work is worse than none: it is read as settled and
    stops the reader looking further.
    """
    from tstack.commands import ui

    # A COMMAND line, not a mention: the message names both in order to warn
    # against them, and a blunt substring check fails on its own disclaimer --
    # the same way a regex guard matches the example in its own docstring.
    offered = [
        line.strip()
        for line in ui.missing().splitlines()
        if line.strip().startswith(("uv tool install", "pipx install"))
    ]
    assert not offered, f"still recommending a tool installer: {offered}"
    # ...and it says why, because a reader will otherwise reach for them.
    assert "entry points" in ui.missing()


def test_the_missing_textual_message_is_probed_per_machine(monkeypatch):
    """Arch has a current textual (8.2.8); Debian 13 has 2.1.2 and Ubuntu 24.04
    still has 0.1.13, old enough that naming `python3-textual` there would send
    someone to a version this app cannot run. So pacman is suggested only on
    Arch, and the PEP 668 override only where the marker actually exists."""
    from tstack.commands import ui

    monkeypatch.setattr(ui.plat, "is_arch", lambda: True)
    assert "pacman -S python-textual" in "\n".join(ui._install_hint())

    monkeypatch.setattr(ui.plat, "is_arch", lambda: False)
    monkeypatch.setattr(ui, "_externally_managed", lambda: True)
    hint = "\n".join(ui._install_hint())
    assert "pacman" not in hint
    assert "--break-system-packages" in hint

    monkeypatch.setattr(ui, "_externally_managed", lambda: False)
    assert "--break-system-packages" not in "\n".join(ui._install_hint())


def test_the_no_install_path_is_offered_when_uv_is_present(monkeypatch):
    """It needs nothing decided and nothing written, so it leads."""
    from tstack.commands import ui

    monkeypatch.setattr(ui.shutil, "which", lambda name: "/usr/bin/uv" if name == "uv" else None)
    assert "uv run --with textual" in "\n".join(ui._install_hint())

    monkeypatch.setattr(ui.shutil, "which", lambda name: None)
    assert "uv run" not in "\n".join(ui._install_hint())


# --- the offer -------------------------------------------------------------
# Correct advice is still a wall: the reader asked for a dashboard and got a
# paragraph and a command to copy. So the command offers to do it -- which means
# it now runs pip on someone's machine, and every one of these tests is about
# what it may not do without being asked.


@pytest.fixture
def _no_ambient_offer(monkeypatch):
    """Neither state of the knob leaking in from the developer's shell. With
    TS_UI_INSTALL=1 set, a test of the DECLINE path would reach the network."""
    monkeypatch.delenv("TS_UI_INSTALL", raising=False)


def test_the_offer_prefers_a_real_install_over_the_no_install_path(monkeypatch):
    """The opposite order from the printed hint, deliberately.

    The hint leads with `uv run --with` because it needs nothing decided. The
    offer is about to fix the problem, and `uv run` resolves into a cache and
    leaves `import textual` no more possible than before -- so the next
    `tstack ui` would ask all over again.
    """
    from tstack.commands import ui

    monkeypatch.setattr(ui.shutil, "which", lambda name: "/usr/bin/uv")
    question, install, run = ui._plan()
    assert install and install[-1] == "textual" and "pip" in install
    assert "Install Textual" in question
    assert run[-1] == "ui" and str(ui.ENTRY) in run

    # Only when pip cannot do it does uv get the job.
    monkeypatch.setattr(ui.importlib.util, "find_spec", lambda name: None)
    question, install, run = ui._plan()
    assert install is None, "uv run installs nothing, so there is nothing to run first"
    assert run[:4] == ["/usr/bin/uv", "run", "--with", "textual"]
    assert "installing nothing" in question

    # Neither: back to printing the explanation.
    monkeypatch.setattr(ui.shutil, "which", lambda name: None)
    assert ui._plan() is None


def test_a_venv_never_gets_the_user_flag(monkeypatch):
    """`pip install --user` inside a virtualenv is an error, not a preference:
    "User site-packages are not visible in this virtualenv"."""
    from tstack.commands import ui

    monkeypatch.setattr(ui.sys, "prefix", "/tmp/venv")
    monkeypatch.setattr(ui.sys, "base_prefix", "/usr")
    assert "--user" not in ui._pip_install()

    monkeypatch.setattr(ui.sys, "prefix", "/usr")
    assert "--user" in ui._pip_install()


def test_the_offer_never_runs_anything_without_being_asked(monkeypatch, _no_ambient_offer):
    """Every path that is not an explicit yes has to leave the machine alone."""
    from tstack.commands import ui

    ran: list[list[str]] = []
    monkeypatch.setattr(ui, "_spawn", lambda argv: ran.append(argv) or 0)
    monkeypatch.setattr(
        ui, "_plan", lambda: ("Install Textual", ["pip", "install", "textual"], ["py", "ui"])
    )

    # No terminal to ask on -- the case that matters, because this is what a
    # hook, a cron line and a piped run all look like.
    monkeypatch.setattr(ui.sys.stdin, "isatty", lambda: False, raising=False)
    assert ui.offer() is None
    assert ran == []

    # Declined.
    monkeypatch.setattr(ui, "_confirm", lambda *a, **k: False)
    assert ui.offer() is None
    assert ran == []

    # Switched off outright.
    monkeypatch.setenv("TS_UI_INSTALL", "0")
    monkeypatch.setattr(ui, "_confirm", lambda *a, **k: True)
    assert ui.offer() is None
    assert ran == []


def test_ts_assume_yes_is_not_consent_to_install(monkeypatch, _no_ambient_offer):
    """It means "take every default", and the default for a real install is no.

    It is also set for every parity container (`tests/parity/run.sh` passes
    -e TS_ASSUME_YES=1), so reading it as consent would have an unattended
    `tstack ui` reach the network and write into site-packages in CI.
    """
    from tstack.commands import ui

    ran: list[list[str]] = []
    monkeypatch.setattr(ui, "_spawn", lambda argv: ran.append(argv) or 0)
    monkeypatch.setattr(
        ui, "_plan", lambda: ("Install Textual", ["pip", "install", "textual"], ["py", "ui"])
    )
    monkeypatch.setattr(ui.sys.stdin, "isatty", lambda: False, raising=False)
    monkeypatch.setenv("TS_ASSUME_YES", "1")
    assert ui.offer() is None
    assert ran == []


def test_yes_installs_then_opens_the_dashboard_and_the_child_cannot_re_offer(
    monkeypatch, _no_ambient_offer
):
    from tstack.commands import ui

    ran: list[list[str]] = []
    monkeypatch.setattr(ui, "_spawn", lambda argv: ran.append(argv) or 0)
    monkeypatch.setattr(
        ui, "_plan", lambda: ("Install Textual", ["pip", "install", "textual"], ["py", "ui"])
    )
    monkeypatch.setenv("TS_UI_INSTALL", "1")
    assert ui.offer() == 0
    assert ran == [["pip", "install", "textual"], ["py", "ui"]], "install first, then the dashboard"


def test_the_child_is_told_not_to_offer_again(monkeypatch):
    """An install that reports success while `import textual` still fails would
    otherwise have the child ask the same question, forever."""
    from tstack.commands import ui

    seen: dict = {}

    def fake_call(argv, env=None):
        seen["argv"], seen["env"] = argv, env
        return 0

    monkeypatch.setattr(ui.subprocess, "call", fake_call)
    monkeypatch.setenv("TS_UI_INSTALL", "1")
    assert ui._spawn(["py", "ui"]) == 0
    assert seen["env"]["TS_UI_INSTALL"] == "0"
    assert seen["env"]["PATH"] == os.environ["PATH"], "the rest of the environment is inherited"


def test_a_child_that_cannot_be_run_is_reported_not_raised(monkeypatch, capsys):
    from tstack.commands import ui

    def boom(argv, env=None):
        raise OSError("no such file")

    monkeypatch.setattr(ui.subprocess, "call", boom)
    assert ui._spawn(["nope", "ui"]) == 1
    assert "could not run nope" in capsys.readouterr().err


def test_a_failed_install_does_not_open_the_dashboard_and_falls_back_to_the_hint(
    monkeypatch, capsys, _no_ambient_offer
):
    from tstack.commands import ui

    ran: list[list[str]] = []
    monkeypatch.setattr(ui, "_spawn", lambda argv: ran.append(argv) or 1)
    monkeypatch.setattr(
        ui, "_plan", lambda: ("Install Textual", ["pip", "install", "textual"], ["py", "ui"])
    )
    monkeypatch.setenv("TS_UI_INSTALL", "1")
    assert ui.offer() is None, "None sends the caller back to the full explanation"
    assert ran == [["pip", "install", "textual"]], "and the dashboard is never started"
    assert "install failed" in capsys.readouterr().err


def test_the_problem_is_named_once_not_twice(monkeypatch, capsys, _no_ambient_offer):
    """The offer has to say what is wrong before it can ask about fixing it, so
    the explanation printed after a decline must not repeat the same line."""
    real_import = __import__

    def no_textual(name, *args, **kwargs):
        if name.startswith("textual") or name.endswith("ui.app"):
            raise ImportError("No module named 'textual'")
        return real_import(name, *args, **kwargs)

    monkeypatch.setattr("builtins.__import__", no_textual)
    monkeypatch.setenv("TS_UI_INSTALL", "0")
    code = ui_cmd.main([])
    monkeypatch.undo()
    assert code == 1
    err = capsys.readouterr().err
    assert err.count(ui_cmd.HEADER) == 1
