"""The read model and the save path behind `tstack ui`. No Textual here.

WHY THE UI DOES NOT WRITE THE STORE ITSELF

`tstack/store.py` is the one writer, and the rule exists because a second one is
how this repo lost five TTS hooks in a day. A dashboard is exactly the kind of
thing that grows its own writer -- it already has the value, the key and the
file path -- so this module routes every save through
`tstack.commands.config.set_value`, the same function the command line uses.

That also gets the schema's validation and the DERIVED refusal for free: a key
regenerated by `chezmoi init` cannot be edited here any more than it can be set
from a shell, and the message is the same one either way.
"""

from __future__ import annotations

import io
from contextlib import redirect_stdout
from dataclasses import dataclass

from .. import schema


@dataclass(frozen=True)
class Row:
    """One setting, flattened for display."""

    key: str
    label: str
    group: str
    kind: str
    value: str
    default: str
    source: str
    note: str
    options: tuple[str, ...]
    flags: frozenset[str]

    @property
    def editable(self) -> bool:
        return schema.DERIVED not in self.flags

    @property
    def display(self) -> str:
        """What to show for a value. An empty string is a real state -- an unset
        `ccTtsSayVoice` means "the system voice" -- so it is named rather than
        rendered as a blank cell that reads like a bug."""
        return self.value if self.value else "(unset)"

    @property
    def after(self) -> str:
        """The one-word consequence of changing it, or "" for none.

        A setting that needs a new shell, a restart, or is written by its own
        standalone path is worth knowing about BEFORE the edit rather than after
        wondering why nothing happened.
        """
        if schema.SHELL in self.flags:
            return "new shell"
        if schema.RESTART in self.flags:
            return "restart"
        return ""


def _strings(value: object) -> tuple[str, ...]:
    """A record field that is a list of strings, from a dict typed `object`.

    `snapshot()` is deliberately loosely typed - it is the JSON read model, and
    JSON has no types worth carrying - so the narrowing happens once, here,
    rather than as an ignore comment at each of the two call sites.
    """
    return tuple(str(item) for item in value) if isinstance(value, list) else ()


def rows() -> list[Row]:
    """Every setting, from the same read model `--json` emits.

    Schema declaration order, not alphabetical: the schema groups related keys
    together and that grouping is the only ordering anyone has thought about.
    """
    return [
        Row(
            key=str(r["key"]),
            label=str(r["label"]),
            group=str(r["group"]),
            kind=str(r["kind"]),
            value=str(r["value"]),
            default=str(r["default"]),
            source=str(r["source"]),
            note=str(r["note"]),
            options=_strings(r["options"]),
            flags=frozenset(_strings(r["flags"])),
        )
        for r in schema.snapshot()
    ]


def match(row: Row, query: str) -> bool:
    """Case-insensitive substring over the fields someone would actually type.

    The NOTE is searched too, which is what makes "gpu", "ollama" or "leader"
    find the setting when its key does not contain the word -- the key names are
    camelCase internals and nobody remembers them.
    """
    if not query:
        return True
    needle = query.lower()
    return any(
        needle in haystack.lower()
        for haystack in (row.key, row.label, row.group, row.value, row.note)
    )


def filter_rows(all_rows: list[Row], query: str) -> list[Row]:
    return [r for r in all_rows if match(r, query)]


def groups(all_rows: list[Row]) -> list[str]:
    """Group names, first-seen order, deduplicated."""
    return list(dict.fromkeys(r.group for r in all_rows))


def changed(row: Row) -> bool:
    """Is this value something other than what the schema ships?

    `source` answers a different question -- where the value was READ from -- and
    a saved value identical to the default is not a change worth flagging.
    """
    return row.value != row.default


def save(key: str, value: str) -> tuple[bool, str]:
    """Write one setting through the command line's own setter.

    Returns (ok, message). Stdout is captured rather than printed: `set_value`
    talks to a terminal this process has handed to Textual, and a stray line
    would land in the middle of the rendered screen.
    """
    from ..commands import config as config_cmd

    setting = schema.BY_KEY.get(key)
    if setting is None:
        return (False, f"unknown setting: {key}")
    reason = setting.validate(value)
    if reason:
        return (False, reason)

    buffer = io.StringIO()
    out = config_cmd.Out(quiet=False)
    try:
        with redirect_stdout(buffer):
            code = config_cmd.set_value(key, value, out, dry_run=False)
    except Exception as exc:  # a save must never take the dashboard down with it
        return (False, f"{type(exc).__name__}: {exc}")
    text = buffer.getvalue().strip().splitlines()
    if code != 0:
        return (False, text[-1] if text else f"failed with exit {code}")
    return (True, f"saved {key} = {value or '(unset)'}")


def next_choice(row: Row, backwards: bool = False) -> str | None:
    """The next allowed value for a choice setting, wrapping.

    Cycling in place is the whole reason a two- or three-value setting does not
    need a dialog: `themeMode` and every on/off pair is one keystroke.
    """
    if row.kind != "choice" or not row.options:
        return None
    try:
        index = row.options.index(row.value)
    except ValueError:
        return row.options[0]
    step = -1 if backwards else 1
    return row.options[(index + step) % len(row.options)]
