"""The Omarchy integration: three files the stack installs into Omarchy's own
extension points, and what keeps them current.

WHY EXTENSION POINTS RATHER THAN CONFIG FILES

Omarchy owns the theme, the fonts and the update cycle, and it publishes
documented seams for each: `~/.config/omarchy/themed/<name>.tpl` (rendered into
`~/.local/state/omarchy/current/theme/<name>` on every theme change) and
`~/.config/omarchy/hooks/<event>.d/<script>`. Using those means the stack never
edits a file Omarchy will overwrite, and `omarchy theme set` keeps working
exactly as it did.

The three artefacts:

  themed/wezterm.lua.tpl        WezTerm's colours, per Omarchy theme. Omarchy
                                themes alacritty, foot, ghostty and kitty and
                                nothing else -- WezTerm gets no theming from it
                                at all -- so this is a capability upstream does
                                not have rather than a copy of one it does.
  hooks/theme-set.d/...         re-bake the light/dark palette and nudge WezTerm
  hooks/post-update.d/...       report a stack update alongside `omarchy update`

WHY WRITING INTO ~/.config/omarchy IS SAFE HERE

That directory is stow-managed on this fleet. These are ADDITIVE files with names
of their own, never edits to a file Omarchy or the stow tree owns -- the same
bargain `~/.config/git/terminal-stack.gitconfig` strikes, and stow links
per-file, so a new sibling is not disturbed.

WHY THERE IS NO SAVED SETTING

`off` is a machine-local sentinel, not a chezmoi [data] key. Adding a key to that
store has a documented seven-step blast radius across the wizard, both config
readers, the toml template and both sync scripts, and this decision is per
machine by nature: the artefacts only exist where Omarchy does. Same shape as the
TTS mute sentinel.
"""

from __future__ import annotations

import os
import shutil
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from . import platform as plat
from . import proc

Say = Callable[[str], None]

# The marker every installed artefact carries. A file at one of these paths
# WITHOUT it belongs to someone else, and the difference between "ours to
# refresh" and "theirs to leave alone" is the whole reason it is there.
OURS = "installed by terminal-stack"

UNSUPPORTED = """omarchy: this is not an Omarchy host.

  The integration installs into Omarchy's own theme templates and event hooks,
  which exist only there. Plain Arch gets the pacman installer and nothing from
  this command."""


def config_home() -> Path:
    raw = os.environ.get("XDG_CONFIG_HOME")
    return Path(raw) if raw else Path.home() / ".config"


def state_home() -> Path:
    raw = os.environ.get("XDG_STATE_HOME")
    return Path(raw) if raw else Path.home() / ".local" / "state"


def off_sentinel() -> Path:
    return plat.state_dir() / "omarchy-integration-off"


def generated_theme() -> Path:
    """Where Omarchy renders our template to, on every `omarchy theme set`."""
    return state_home() / "omarchy" / "current" / "theme" / "wezterm.lua"


# ---- the artefacts ----------------------------------------------------------
#
# Content is built by pure functions so the whole set is testable with no Omarchy
# and no filesystem: `artefacts()` is a value, and installing it is the only part
# that touches disk.


@dataclass(frozen=True)
class Artefact:
    path: Path
    content: str
    executable: bool


def _wezterm_tpl() -> str:
    """Omarchy's template language is `sed`: `{{ key }}` -> the theme's value.

    The values arrive with their leading `#`, which is why every one of them is
    quoted here and bare in Omarchy's own ghostty template. `mode` is the key
    that matters most -- it is light/dark straight from the theme, so the stack
    stops having to infer it from gsettings.
    """
    # NOT an f-string: the body is full of Omarchy's `{{ key }}` tokens AND of
    # Lua's own braces, so interpolation would mean doubling every one of them
    # and the template would stop being readable as the file it produces. The
    # ownership marker is concatenated in instead -- and it has to be on ONE
    # line, because that is what `_is_ours` greps for. Wrapped across two lines
    # it read as somebody else's file, and every sync politely refused to
    # refresh its own template.
    return (
        "-- WezTerm colours for the active Omarchy theme. "
        + OURS
        + ".\n"
        + """--
-- Rendered by `omarchy theme set` from the template at
-- ~/.config/omarchy/themed/wezterm.lua.tpl. Do not edit this file: it is
-- regenerated on every theme change. Edit the template instead.
--
-- Omarchy themes alacritty, foot, ghostty and kitty out of the box, and nothing
-- else. This is the same treatment for WezTerm.
return {
  mode = "{{ mode }}",
  background = "{{ background }}",
  foreground = "{{ foreground }}",
  cursor = "{{ cursor }}",
  selection_bg = "{{ selection_background }}",
  selection_fg = "{{ selection_foreground }}",
  accent = "{{ accent }}",
  muted = "{{ muted }}",
  tab_bar_bg = "{{ dark_background }}",
  ansi = {
    "{{ background }}", "{{ red }}", "{{ green }}", "{{ yellow }}",
    "{{ blue }}", "{{ magenta }}", "{{ cyan }}", "{{ foreground }}",
  },
  brights = {
    "{{ muted }}", "{{ bright_red }}", "{{ bright_green }}", "{{ bright_yellow }}",
    "{{ bright_blue }}", "{{ bright_magenta }}", "{{ bright_cyan }}", "{{ bright_foreground }}",
  },
}
"""
    )


def _clone_resolution() -> str:
    """The shell prologue every hook shares.

    Resolved at RUN time, never baked. `tstack doctor --repair` relocates a
    legacy clone, and a hook holding a stale absolute path would fail on every
    theme change with nothing to connect it to the move. Exits 0 when no clone is
    found: a hook that errors on every desktop event is worse than no hook.
    """
    return """for _d in "${TERMINAL_STACK_DIR:-}" \\
           "${XDG_DATA_HOME:-$HOME/.local/share}/terminal-stack" \\
           "$HOME/.local/share/terminal-stack"; do
    [ -n "$_d" ] && [ -f "$_d/tstack/main.py" ] && TS_CLONE="$_d" && break
done
[ -n "${TS_CLONE:-}" ] || exit 0
command -v python3 >/dev/null 2>&1 || exit 0
"""


def _theme_hook() -> str:
    return f"""#!/usr/bin/env bash
# {OURS}. Runs after `omarchy theme set` (theme slug in $1).
#
# Two jobs, and neither is "re-render everything": a full apply on every theme
# switch is slow, noisy, and would fight the user mid-flick through the theme
# picker.
#
#   1. Re-bake the light/dark palette IF the mode actually flipped. Omarchy's
#      colors.toml carries `mode` directly, so this no longer has to be inferred
#      from gsettings -- and comparing first is what keeps a dark->dark theme
#      change free.
#   2. Touch the WezTerm config so running instances reload. WezTerm watches its
#      OWN config file, not the generated theme file beside it, so a change to
#      the latter reaches nothing until the former is touched.
set -u
{_clone_resolution()}
exec python3 "$TS_CLONE/tstack/main.py" omarchy theme-changed "${{1:-}}"
"""


def _update_hook() -> str:
    return f"""#!/usr/bin/env bash
# {OURS}. Runs during `omarchy update`, after system packages and migrations.
#
# It REPORTS; it does not pull. `tstack update` is a zsh function today
# (commands.conf: `update  @_tstack_update`), and it carries real behaviour --
# the dirty-clone refusal, the rollback point, the duplicate-clone warning --
# that a hook cannot call from bash and must not reimplement. Ordering is still
# the point: this runs after Omarchy's migrations, so what it reports is
# measured against the system you now have.
set -u
{_clone_resolution()}
exec python3 "$TS_CLONE/tstack/main.py" omarchy update-check
"""


def artefacts() -> list[Artefact]:
    """PURE. Every file the integration owns, wherever it would go."""
    cfg = config_home() / "omarchy"
    return [
        Artefact(cfg / "themed" / "wezterm.lua.tpl", _wezterm_tpl(), False),
        Artefact(cfg / "hooks" / "theme-set.d" / "terminal-stack", _theme_hook(), True),
        Artefact(cfg / "hooks" / "post-update.d" / "terminal-stack", _update_hook(), True),
    ]


# ---- actions ----------------------------------------------------------------


def _is_ours(path: Path) -> bool:
    try:
        return OURS in path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def supported() -> bool:
    return plat.is_omarchy()


def enabled() -> bool:
    return not off_sentinel().exists()


def sync(say: Say) -> int:
    """Install or refresh every artefact. Idempotent; safe on every apply.

    Refuses to overwrite a file at one of our paths that is NOT ours -- a
    hand-written hook with the same name is a deliberate act, and clobbering it
    silently is the failure this repo keeps writing tests about.
    """
    if not supported():
        say(UNSUPPORTED)
        return 2
    if not enabled():
        say("==> omarchy integration is off on this machine (tstack omarchy on)")
        return 0

    changed = 0
    for art in artefacts():
        if art.path.exists() and not _is_ours(art.path):
            say(f"  skip  {art.path}  (not ours; left alone)")
            continue
        try:
            current = art.path.read_text(encoding="utf-8")
        except OSError:
            current = None
        if current == art.content:
            continue
        art.path.parent.mkdir(parents=True, exist_ok=True)
        art.path.write_text(art.content, encoding="utf-8")
        if art.executable:
            art.path.chmod(0o755)
        say(f"  write {art.path}")
        changed += 1

    if changed:
        say(f"==> omarchy integration: {changed} file(s) updated")
        say('    run `omarchy theme set "$(omarchy theme current)"` to render the theme now')
    else:
        say("==> omarchy integration: up to date")
    return 0


def turn_off(say: Say) -> int:
    """Remove the artefacts and remember that, on THIS machine.

    Per machine because the artefacts are per machine: they only exist where
    Omarchy does, and a shared setting would have to be explained on every box
    that never had them.
    """
    if not supported():
        say(UNSUPPORTED)
        return 2
    removed = 0
    for art in artefacts():
        if art.path.exists() and _is_ours(art.path):
            art.path.unlink()
            say(f"  remove {art.path}")
            removed += 1
    sentinel = off_sentinel()
    sentinel.parent.mkdir(parents=True, exist_ok=True)
    sentinel.write_text("tstack omarchy off\n", encoding="utf-8")
    say(f"==> omarchy integration off ({removed} file(s) removed)")
    say("    WezTerm keeps its baked light/dark palette; `omarchy theme set` no longer reaches it.")
    return 0


def turn_on(say: Say) -> int:
    if not supported():
        say(UNSUPPORTED)
        return 2
    sentinel = off_sentinel()
    if sentinel.exists():
        sentinel.unlink()
    return sync(say)


def status(say: Say) -> int:
    if not supported():
        say(UNSUPPORTED)
        return 2
    say(f"omarchy      {plat.distro()} (ID_LIKE={plat.distro_like() or '-'})")
    say(f"integration  {'on' if enabled() else 'off'}")
    for art in artefacts():
        if not art.path.exists():
            state = "missing"
        elif not _is_ours(art.path):
            state = "NOT OURS"
        elif art.path.read_text(encoding="utf-8") != art.content:
            state = "stale (run: tstack omarchy sync)"
        else:
            state = "current"
        say(f"  {state:<28} {art.path}")
    gen = generated_theme()
    say(f"  {'rendered' if gen.exists() else 'not rendered yet':<28} {gen}")
    theme = _run(["omarchy-theme-current"])
    if theme:
        say(f"active theme {theme}")
    return 0


def _run(argv: list[str]) -> str:
    if not shutil.which(argv[0]):
        return ""
    out = proc.capture(argv, timeout=30)
    return "" if out is None else out.stdout.strip()


def theme_mode() -> str:
    """light|dark for the ACTIVE Omarchy theme, or "" when it cannot be read.

    Straight from the theme's own colors.toml via `omarchy-theme-color`, which
    already resolves the three ways a theme can declare it (an explicit
    `mode = "light"`, a legacy marker file, or background luminance for a user
    theme). Far better than the gsettings probe the stack falls back to, which is
    a second-hand copy Omarchy writes.
    """
    colors = state_home() / "omarchy" / "current" / "theme" / "colors.toml"
    if not colors.exists():
        return ""
    mode = _run(["omarchy-theme-color", "--file", str(colors), "mode"])
    return mode if mode in ("light", "dark") else ""
