"""What every saved setting IS: type, allowed values, default, and where it came from.

Modelled on `bootstrap/tts-daemon/ttsd/settings_schema.py`, which already does
this for the daemon's own 72 runtime fields and is fronted by a web dashboard.
That file is the reason its dashboard can be trusted: it shows **which layer won**
per field, so a value that looks right for the wrong reason is visible.

The two field counts are different things and neither is the "43" the docs used
to quote: the daemon describes its merged runtime JSON, while this file describes
the 41 `ccTts*` keys that live in chezmoi `[data]` -- the set `ts_cc_tts_default`
and `ts_cc_tts_keys` both enumerate, which `tests/test_store.py` pins.

The same problem exists one level up. A key can come from chezmoi `[data]`, from
the Windows `config.json` mirror, or from nothing at all - and those three cases
look identical once the value is printed. On 2026-08-21 the mirror said one
thing, `[data]` said another, the pwsh sync had deleted every TTS hook, and every
report still looked healthy.

DERIVED keys are not settings. `leaderKey`, `leaderMods`, `tmuxPrefixResolved`
and `resolvedTheme` are regenerated by `chezmoi init` from the keys the user
actually chose. Writing one directly produces a value that survives exactly until
the next save, so they are marked and never offered as writable.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from . import store

# Flags, matching the vocabulary ttsd/settings_schema.py already uses.
DERIVED = "derived"  # regenerated by `chezmoi init`; never write it directly
RESTART = "restart"  # needs a restart of something before it takes effect
SHELL = "shell"  # needs a new shell before it takes effect
STANDALONE = "standalone"  # has its own writer; not part of a bulk save


@dataclass(frozen=True)
class Setting:
    key: str
    label: str
    kind: str  # choice | text | list
    group: str
    default: str = ""
    options: tuple[str, ...] = ()
    note: str = ""
    # Dotted path in the Windows mirror when it is not the auto-derived
    # `ccTtsX` -> `ccTts.x`. The mirror nests (`ccTts.kokoro.voice`) and renames
    # (`ccTtsKokoroTimeout` -> `timeoutSec`), so the derivation is wrong for most
    # of the TTS block and silently missed, falling through to the default.
    mirror: str = ""
    flags: frozenset[str] = field(default_factory=frozenset)

    def validate(self, value: str) -> str | None:
        """None when acceptable, else why not - phrased for a user, not a log."""
        if DERIVED in self.flags:
            return (
                f"{self.key} is derived from your other choices and regenerated by "
                f"chezmoi; setting it directly would last until the next save"
            )
        if self.options and value not in self.options:
            return f"{self.key} must be one of: {', '.join(self.options)}"
        if self.kind == "text" and not value.strip():
            return f"{self.key} cannot be empty"
        return None


SETTINGS: tuple[Setting, ...] = (
    Setting(
        "leaderChord",
        "WezTerm leader",
        "text",
        "keys",
        "ctrl-space",
        note="e.g. ctrl-space, ctrl-a, alt-x",
        flags=frozenset({SHELL}),
    ),
    Setting("leaderKey", "WezTerm leader key", "text", "keys", flags=frozenset({DERIVED})),
    Setting("leaderMods", "WezTerm leader modifiers", "text", "keys", flags=frozenset({DERIVED})),
    Setting(
        "tmuxPrefix",
        "tmux prefix",
        "text",
        "keys",
        "ctrl-b",
        note="e.g. ctrl-b, ctrl-a",
        flags=frozenset({SHELL}),
    ),
    Setting(
        "tmuxPrefixResolved", "tmux prefix, resolved", "text", "keys", flags=frozenset({DERIVED})
    ),
    Setting(
        "themeMode",
        "Theme",
        "choice",
        "appearance",
        "dark",
        options=("dark", "light", "follow"),
        note="follow tracks the OS light/dark setting",
    ),
    Setting(
        "resolvedTheme",
        "Baked palette",
        "choice",
        "appearance",
        options=("dark", "light"),
        flags=frozenset({DERIVED}),
    ),
    Setting("apps", "Installed CLI tools", "list", "apps", note="installs only; never uninstalls"),
    Setting(
        "weztermMux",
        "WezTerm mux domain",
        "choice",
        "wezterm",
        "off",
        options=("on", "off"),
        note="config changes need `tstack mux restart`, which kills every pane",
        flags=frozenset({STANDALONE, RESTART}),
    ),
    Setting(
        "weztermRestore",
        "Reopen last session",
        "choice",
        "wezterm",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "starshipPreset",
        "Prompt",
        "text",
        "appearance",
        "terminal-stack",
        note=(
            "terminal-stack is this repo's own prompt; any other value is one of "
            "starship's built-in presets. `tstack config prompt list` renders each"
        ),
        flags=frozenset({SHELL}),
    ),
    Setting(
        "atuinEnabled",
        "atuin owns Ctrl+R",
        "choice",
        "shell",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE, SHELL}),
    ),
    Setting(
        "ghosttyConfig",
        "Managed Ghostty config",
        "choice",
        "appearance",
        "on",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "memoryBackend",
        "Memory backend",
        "choice",
        "agents",
        "agentmemory",
        options=("agentmemory", "headroom", "none"),
        note="one slot, so two memory systems are unrepresentable",
        flags=frozenset({STANDALONE, RESTART}),
    ),
    Setting(
        "agentmemoryEnabled",
        "AgentMemory",
        "choice",
        "agents",
        "off",
        options=("on", "off"),
        note="derived from memoryBackend; nothing else may write it",
        flags=frozenset({DERIVED}),
    ),
    Setting(
        "headroomEnabled",
        "Headroom",
        "choice",
        "agents",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "headroomCursorMode",
        "Headroom in Cursor",
        "choice",
        "agents",
        "mcp",
        options=("mcp", "byok", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "cavemanEnabled",
        "Caveman",
        "choice",
        "agents",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "playwrightEnabled",
        "Playwright MCP",
        "choice",
        "agents",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsEnabled",
        "Voice notifications",
        "choice",
        "tts",
        "false",
        options=("true", "false"),
        mirror="ccTts.enabled",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsDaemon",
        "TTS daemon",
        "choice",
        "tts",
        "off",
        options=("on", "off"),
        mirror="ccTts.daemon.enabled",
        flags=frozenset({STANDALONE, RESTART}),
    ),
    Setting(
        "ccTtsEngine",
        "TTS engine",
        "choice",
        "tts",
        "kokoro",
        options=("kokoro", "chatterbox", "say", "auto"),
        mirror="ccTts.engine",
        note="auto tries kokoro then chatterbox; say is macOS-only and is also "
        "the floor every other engine falls back to; edge-tts is a fallback only",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsMessageMode",
        "What it says",
        "choice",
        "tts",
        "template",
        options=("template", "hook"),
        mirror="ccTts.messageMode",
        note="template is a fixed sentence; hook lets the agent write it",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsEvents",
        "Speak on",
        "list",
        "tts",
        "waiting,error,question,permission",
        mirror="ccTts.events",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsIncludeProject",
        "Name the project",
        "choice",
        "tts",
        "true",
        options=("true", "false"),
        mirror="ccTts.includeProject",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsExcitement",
        "Excitement",
        "text",
        "tts",
        "0.25",
        mirror="ccTts.excitement",
        note="0 to 1. Drives kokoro speed and chatterbox exaggeration",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsMaxChars",
        "Maximum characters",
        "text",
        "tts",
        "120",
        mirror="ccTts.maxChars",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsDebounceSec",
        "Debounce (seconds)",
        "text",
        "tts",
        "5",
        mirror="ccTts.debounceSec",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsPlayer",
        "Player",
        "choice",
        "tts",
        "auto",
        options=("auto", "windows", "ffplay"),
        mirror="ccTts.player",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsKokoroUrl",
        "Kokoro URL",
        "text",
        "tts-voice",
        "http://127.0.0.1:8880",
        mirror="ccTts.kokoro.url",
        note="any OpenAI-compatible /v1/audio/speech server, including mlx-audio",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsKokoroModel",
        "Kokoro model id",
        "text",
        "tts-voice",
        "kokoro",
        mirror="ccTts.kokoro.model",
        note=(
            "the docker image answers to `kokoro`; mlx-audio wants the HuggingFace "
            "repo id, e.g. mlx-community/Kokoro-82M-bf16"
        ),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsKokoroVoice",
        "Kokoro voice",
        "text",
        "tts-voice",
        "am_adam",
        mirror="ccTts.kokoro.voice",
        note="`tstack config tts voices` lists what the server actually offers",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsKokoroSpeed",
        "Kokoro speed",
        "text",
        "tts-voice",
        "1.0",
        mirror="ccTts.kokoro.speed",
        note="only used when excitement is unset",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsKokoroFormat",
        "Kokoro format",
        "choice",
        "tts-voice",
        "mp3",
        options=("mp3", "wav", "opus", "flac"),
        mirror="ccTts.kokoro.format",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsKokoroTimeout",
        "Kokoro timeout (seconds)",
        "text",
        "tts-voice",
        "15",
        mirror="ccTts.kokoro.timeoutSec",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsChatterboxUrl",
        "Chatterbox URL",
        "text",
        "tts-voice",
        "http://127.0.0.1:8881",
        mirror="ccTts.chatterbox.url",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsChatterboxVoice",
        "Chatterbox voice",
        "text",
        "tts-voice",
        "adam",
        mirror="ccTts.chatterbox.voice",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsChatterboxEnergy",
        "Chatterbox energy",
        "text",
        "tts-voice",
        "0.25",
        mirror="ccTts.chatterbox.energy",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsChatterboxCfgWeight",
        "Chatterbox cfg weight",
        "text",
        "tts-voice",
        "0.5",
        mirror="ccTts.chatterbox.cfgWeight",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsChatterboxTemperature",
        "Chatterbox temperature",
        "text",
        "tts-voice",
        "0.6",
        mirror="ccTts.chatterbox.temperature",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsChatterboxTimeout",
        "Chatterbox timeout (seconds)",
        "text",
        "tts-voice",
        "60",
        mirror="ccTts.chatterbox.timeoutSec",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsSayVoice",
        "macOS system voice",
        "text",
        "tts-voice",
        "",
        mirror="ccTts.say.voice",
        note="empty means the system voice; `tstack config tts voices` lists and samples them",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsEdgeEnabled",
        "edge-tts fallback",
        "choice",
        "tts-voice",
        "true",
        options=("true", "false"),
        mirror="ccTts.edge.enabled",
        note="only reachable when edge-tts is on PATH",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsEdgeVoice",
        "edge-tts voice",
        "text",
        "tts-voice",
        "en-US-AndrewMultilingualNeural",
        mirror="ccTts.edge.voice",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsVoicePool",
        "Daemon voice pool",
        "list",
        "tts-voice",
        "am_adam,am_michael,af_heart,bm_george",
        mirror="ccTts.voicePool",
        note="read only by the Windows daemon's per-session rotation",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsPrefixClaude",
        "Claude prefix",
        "text",
        "tts-message",
        "Claude",
        mirror="ccTts.prefixClaude",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsPrefixCursor",
        "Cursor prefix",
        "text",
        "tts-message",
        "Cursor",
        mirror="ccTts.prefixCursor",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsPrefixCodex",
        "Codex prefix",
        "text",
        "tts-message",
        "Codex",
        mirror="ccTts.prefixCodex",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsPrefixClaudeEnabled",
        "Say the Claude prefix",
        "choice",
        "tts-message",
        "true",
        options=("true", "false"),
        mirror="ccTts.prefixClaudeEnabled",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsPrefixCursorEnabled",
        "Say the Cursor prefix",
        "choice",
        "tts-message",
        "true",
        options=("true", "false"),
        mirror="ccTts.prefixCursorEnabled",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsPrefixCodexEnabled",
        "Say the Codex prefix",
        "choice",
        "tts-message",
        "true",
        options=("true", "false"),
        mirror="ccTts.prefixCodexEnabled",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsTemplateWaiting",
        "Template: waiting",
        "text",
        "tts-message",
        "Done in {project}. I'm waiting for you.",
        mirror="ccTts.templates.waiting",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsTemplateError",
        "Template: error",
        "text",
        "tts-message",
        "Error in {project}. You may want to look.",
        mirror="ccTts.templates.error",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsTemplateQuestion",
        "Template: question",
        "text",
        "tts-message",
        "I have a question for you.",
        mirror="ccTts.templates.question",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsTemplatePermission",
        "Template: permission",
        "text",
        "tts-message",
        "Permission needed in {project}.",
        mirror="ccTts.templates.permission",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsDaemonPort",
        "Daemon port",
        "text",
        "tts-daemon",
        "8890",
        mirror="ccTts.daemon.port",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsSummarizer",
        "Summarizer",
        "choice",
        "tts-daemon",
        "template",
        options=("template", "self", "haiku", "ollama"),
        mirror="ccTts.summarize.mode",
        note="haiku and ollama need the daemon, which is Windows-only",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsHaikuModel",
        "Haiku model",
        "text",
        "tts-daemon",
        "claude-haiku-4-5",
        mirror="ccTts.summarize.haikuModel",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsOllamaUrl",
        "Ollama URL",
        "text",
        "tts-daemon",
        "http://127.0.0.1:11434",
        mirror="ccTts.summarize.ollamaUrl",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsOllamaModel",
        "Ollama model",
        "text",
        "tts-daemon",
        "llama3.2:3b",
        mirror="ccTts.summarize.ollamaModel",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsMusicMode",
        "Music while speaking",
        "choice",
        "tts-daemon",
        "duck",
        options=("duck", "smart", "pause", "off"),
        mirror="ccTts.music.mode",
        note="daemon-only; refused on macOS",
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsDuckPercent",
        "Duck to (%)",
        "text",
        "tts-daemon",
        "30",
        mirror="ccTts.music.duckPercent",
        note="daemon-only",
        flags=frozenset({STANDALONE}),
    ),
)

BY_KEY = {s.key: s for s in SETTINGS}
GROUPS = tuple(dict.fromkeys(s.group for s in SETTINGS))

# Where a value came from. Printing a value without this is how a setting that
# looks right for the wrong reason survives.
FROM_CHEZMOI = "chezmoi"
FROM_MIRROR = "mirror"
FROM_DEFAULT = "default"
UNSET = "unset"


def source_of(key: str) -> str:
    """Which layer supplies this key's current value."""
    data = store.chezmoi_data()
    if data.get(key):
        return FROM_CHEZMOI
    mirrored = store.mirror_value(key)
    if mirrored not in (store.MISSING, ""):
        return FROM_MIRROR
    setting = BY_KEY.get(key)
    if setting and setting.default:
        return FROM_DEFAULT
    return UNSET


def describe(key: str) -> dict[str, object]:
    """One setting as a record: value, default, source, and its metadata."""
    setting = BY_KEY[key]
    return {
        "key": setting.key,
        "label": setting.label,
        "kind": setting.kind,
        "group": setting.group,
        "value": store.get(key),
        "default": setting.default,
        "options": list(setting.options),
        "source": source_of(key),
        "note": setting.note,
        "flags": sorted(setting.flags),
    }


def snapshot() -> list[dict[str, object]]:
    """Every setting, in declaration order. The read model `--json` emits."""
    return [describe(s.key) for s in SETTINGS]
