"""What every saved setting IS: type, allowed values, default, and where it came from.

Modelled on `bootstrap/tts-daemon/ttsd/settings_schema.py`, which already does
this for the 43 TTS keys and is fronted by a web dashboard. That file is the
reason its dashboard can be trusted: it shows **which layer won** per field, so a
value that looks right for the wrong reason is visible.

The same problem exists one level up. A key can come from chezmoi `[data]`, from
the Windows `config.json` mirror, or from nothing at all - and those three cases
look identical once the value is printed. On 2026-08-21 the mirror said one
thing, `[data]` said another, the pwsh sync had deleted every TTS hook, and every
report still looked healthy.

DERIVED keys are not settings. `leaderKey`, `leaderMods`, `tmuxPrefixResolved`
and `resolvedTheme` are regenerated by `chezmoi init` from the keys the user
actually chose. Writing one directly produces a value that survives exactly until
the next save, so they are marked and never offered as writable.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from . import store

# Flags, matching the vocabulary ttsd/settings_schema.py already uses.
DERIVED = "derived"  # regenerated by `chezmoi init`; never write it directly
RESTART = "restart"  # needs a restart of something before it takes effect
SHELL = "shell"  # needs a new shell before it takes effect
STANDALONE = "standalone"  # has its own writer; not part of a bulk save


@dataclass(frozen=True)
class Setting:
    key: str
    label: str
    kind: str  # choice | text | list
    group: str
    default: str = ""
    options: tuple[str, ...] = ()
    note: str = ""
    flags: frozenset[str] = field(default_factory=frozenset)

    def validate(self, value: str) -> str | None:
        """None when acceptable, else why not - phrased for a user, not a log."""
        if DERIVED in self.flags:
            return (
                f"{self.key} is derived from your other choices and regenerated by "
                f"chezmoi; setting it directly would last until the next save"
            )
        if self.options and value not in self.options:
            return f"{self.key} must be one of: {', '.join(self.options)}"
        if self.kind == "text" and not value.strip():
            return f"{self.key} cannot be empty"
        return None


SETTINGS: tuple[Setting, ...] = (
    Setting(
        "leaderChord",
        "WezTerm leader",
        "text",
        "keys",
        "ctrl-space",
        note="e.g. ctrl-space, ctrl-a, alt-x",
        flags=frozenset({SHELL}),
    ),
    Setting("leaderKey", "WezTerm leader key", "text", "keys", flags=frozenset({DERIVED})),
    Setting("leaderMods", "WezTerm leader modifiers", "text", "keys", flags=frozenset({DERIVED})),
    Setting(
        "tmuxPrefix",
        "tmux prefix",
        "text",
        "keys",
        "ctrl-b",
        note="e.g. ctrl-b, ctrl-a",
        flags=frozenset({SHELL}),
    ),
    Setting(
        "tmuxPrefixResolved", "tmux prefix, resolved", "text", "keys", flags=frozenset({DERIVED})
    ),
    Setting(
        "themeMode",
        "Theme",
        "choice",
        "appearance",
        "dark",
        options=("dark", "light", "follow"),
        note="follow tracks the OS light/dark setting",
    ),
    Setting(
        "resolvedTheme",
        "Baked palette",
        "choice",
        "appearance",
        options=("dark", "light"),
        flags=frozenset({DERIVED}),
    ),
    Setting("apps", "Installed CLI tools", "list", "apps", note="installs only; never uninstalls"),
    Setting(
        "weztermMux",
        "WezTerm mux domain",
        "choice",
        "wezterm",
        "off",
        options=("on", "off"),
        note="config changes need `tstack mux restart`, which kills every pane",
        flags=frozenset({STANDALONE, RESTART}),
    ),
    Setting(
        "weztermRestore",
        "Reopen last session",
        "choice",
        "wezterm",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "atuinEnabled",
        "atuin owns Ctrl+R",
        "choice",
        "shell",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE, SHELL}),
    ),
    Setting(
        "ghosttyConfig",
        "Managed Ghostty config",
        "choice",
        "appearance",
        "on",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "memoryBackend",
        "Memory backend",
        "choice",
        "agents",
        "agentmemory",
        options=("agentmemory", "headroom", "none"),
        note="one slot, so two memory systems are unrepresentable",
        flags=frozenset({STANDALONE, RESTART}),
    ),
    Setting(
        "agentmemoryEnabled",
        "AgentMemory",
        "choice",
        "agents",
        "off",
        options=("on", "off"),
        note="derived from memoryBackend; nothing else may write it",
        flags=frozenset({DERIVED}),
    ),
    Setting(
        "headroomEnabled",
        "Headroom",
        "choice",
        "agents",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "headroomCursorMode",
        "Headroom in Cursor",
        "choice",
        "agents",
        "mcp",
        options=("mcp", "byok", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "cavemanEnabled",
        "Caveman",
        "choice",
        "agents",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "playwrightEnabled",
        "Playwright MCP",
        "choice",
        "agents",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsEnabled",
        "Voice notifications",
        "choice",
        "tts",
        "false",
        options=("true", "false"),
        flags=frozenset({STANDALONE}),
    ),
    Setting(
        "ccTtsDaemon",
        "TTS daemon",
        "choice",
        "tts",
        "off",
        options=("on", "off"),
        flags=frozenset({STANDALONE, RESTART}),
    ),
    Setting(
        "ccTtsEngine",
        "TTS engine",
        "choice",
        "tts",
        "kokoro",
        options=("kokoro", "chatterbox", "edge"),
        flags=frozenset({STANDALONE}),
    ),
)

BY_KEY = {s.key: s for s in SETTINGS}
GROUPS = tuple(dict.fromkeys(s.group for s in SETTINGS))

# Where a value came from. Printing a value without this is how a setting that
# looks right for the wrong reason survives.
FROM_CHEZMOI = "chezmoi"
FROM_MIRROR = "mirror"
FROM_DEFAULT = "default"
UNSET = "unset"


def source_of(key: str) -> str:
    """Which layer supplies this key's current value."""
    data = store.chezmoi_data()
    if data.get(key):
        return FROM_CHEZMOI
    mirrored = store.mirror_value(key)
    if mirrored not in (store.MISSING, ""):
        return FROM_MIRROR
    setting = BY_KEY.get(key)
    if setting and setting.default:
        return FROM_DEFAULT
    return UNSET


def describe(key: str) -> dict[str, object]:
    """One setting as a record: value, default, source, and its metadata."""
    setting = BY_KEY[key]
    return {
        "key": setting.key,
        "label": setting.label,
        "kind": setting.kind,
        "group": setting.group,
        "value": store.get(key),
        "default": setting.default,
        "options": list(setting.options),
        "source": source_of(key),
        "note": setting.note,
        "flags": sorted(setting.flags),
    }


def snapshot() -> list[dict[str, object]]:
    """Every setting, in declaration order. The read model `--json` emits."""
    return [describe(s.key) for s in SETTINGS]
